
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: data_caddy_development

test:
  <<: *default
  database: data_caddy_test

production:
  <<: *default
  database: data_caddy_production
  username: mbullard
  password: <%= ENV['SOME_APP_DATABASE_PASSWORD'] %>