# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 308b67c350d1ccddbf34b396b572e51b874fa719d90879605a9d35a96c65c7371c177352e79d23b69d23b10aae62f89fbb3e2c20b25fa8d86b8341074a0f9bbc

test:
  secret_key_base: 5b7965434ef92e8b4cf1c69cf5185699e1e1fa438e5f2256e0359c7471375b9d8f2fb7a17804592bee4d1ad15ff68c168f69338c47828d4c4abe0a74877f1b14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
