# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

jeffery = Player.create!(name: "Jeffery Lebowski", email: "jeffery@golfer.com", password: "jeffery1234", password_confirmation: "jeffery1234")
Player.create!(name: "Walter Sobchak",   email: "walter@golfer.com",  password: "walter1234",  password_confirmation: "walter1234")

one_wood = Club.create!(name: "1 Wood", head: "wood", shaft: "steel", abbreviation: "1w")
three_wood = Club.create!(name: "3 Wood", head: "wood", shaft: "steel", abbreviation: "3w")
five_wood = Club.create!(name: "5 Wood", head: "wood", shaft: "steel", abbreviation: "5w")
three_iron = Club.create!(name: "3 Iron", head: "iron", shaft: "steel", abbreviation: "3i")
four_iron = Club.create!(name: "4 Iron", head: "iron", shaft: "steel", abbreviation: "4i")
five_iron = Club.create!(name: "5 Iron", head: "iron", shaft: "steel", abbreviation: "5i")
six_iron = Club.create!(name: "6 Iron", head: "iron", shaft: "steel", abbreviation: "6i")
seven_iron = Club.create!(name: "7 Iron", head: "iron", shaft: "steel", abbreviation: "7i")
eight_iron = Club.create!(name: "8 Iron", head: "iron", shaft: "steel", abbreviation: "8i")
nine_iron = Club.create!(name: "9 Iron", head: "iron", shaft: "steel", abbreviation: "9i")
pitching_wedge = Club.create!(name: "Pitching Wedge", shaft: "steel", head: "wedge", abbreviation: "Pw")
sand_wedge = Club.create!(name: "Sand Wedge", shaft: "steel", head: "wedge", abbreviation: "Sw")
trouble_wedge = Club.create!(name: "Trouble Wedge", shaft: "steel", head: "wedge", abbreviation: "Tw")
putter = Club.create!(name: "Putter", head: "putter", shaft: "steel", abbreviation: "P")

timber_terrace = Course.create!(name: "Timber Terrace")
bogus_course = Course.create!(name: "Bogus Course")

timber_terrace_one = Hole.create!(number: 1, par: 5, distance: 453, course_id: timber_terrace.id)
timber_terrace_two = Hole.create!(number: 2, par: 4, distance: 347, course_id: timber_terrace.id)
timber_terrace_three = Hole.create!(number: 3, par: 4, distance: 236, course_id: timber_terrace.id)
timber_terrace_four = Hole.create!(number: 4, par: 3, distance: 162, course_id: timber_terrace.id)
timber_terrace_five = Hole.create!(number: 5, par: 4, distance: 340, course_id: timber_terrace.id)
timber_terrace_six = Hole.create!(number: 6, par: 3, distance: 147, course_id: timber_terrace.id)
timber_terrace_seven = Hole.create!(number: 7, par: 4, distance: 391, course_id: timber_terrace.id)
timber_terrace_eight = Hole.create!(number: 8, par: 3, distance: 158, course_id: timber_terrace.id)
timber_terrace_nine = Hole.create!(number: 9, par: 5, distance: 510, course_id: timber_terrace.id)

Hole.create!(number: 1, par: 5, distance: 453, course_id: bogus_course.id)
Hole.create!(number: 2, par: 4, distance: 347, course_id: bogus_course.id)
Hole.create!(number: 3, par: 4, distance: 236, course_id: bogus_course.id)
Hole.create!(number: 4, par: 3, distance: 162, course_id: bogus_course.id)
Hole.create!(number: 5, par: 4, distance: 340, course_id: bogus_course.id)
Hole.create!(number: 6, par: 3, distance: 147, course_id: bogus_course.id)
Hole.create!(number: 7, par: 4, distance: 391, course_id: bogus_course.id)
Hole.create!(number: 8, par: 3, distance: 158, course_id: bogus_course.id)
Hole.create!(number: 9, par: 5, distance: 510, course_id: bogus_course.id)
Hole.create!(number: 10, par: 5, distance: 453, course_id: bogus_course.id)
Hole.create!(number: 11, par: 4, distance: 347, course_id: bogus_course.id)
Hole.create!(number: 12, par: 4, distance: 236, course_id: bogus_course.id)
Hole.create!(number: 13, par: 3, distance: 162, course_id: bogus_course.id)
Hole.create!(number: 14, par: 4, distance: 340, course_id: bogus_course.id)
Hole.create!(number: 15, par: 3, distance: 147, course_id: bogus_course.id)
Hole.create!(number: 16, par: 4, distance: 391, course_id: bogus_course.id)
Hole.create!(number: 17, par: 3, distance: 158, course_id: bogus_course.id)
Hole.create!(number: 18, par: 5, distance: 510, course_id: bogus_course.id)

round = Round.create!(date: "2015-05-18", score: 63, finished: true, course: timber_terrace, player: jeffery)

played_hole_one = PlayedHole.create!(hole_id: timber_terrace_one.id, round_id: round.id, player_id: jeffery.id)
played_hole_two = PlayedHole.create!(hole_id: timber_terrace_two.id, round_id: round.id, player_id: jeffery.id)
played_hole_three = PlayedHole.create!(hole_id: timber_terrace_three.id, round_id: round.id, player_id: jeffery.id)
played_hole_four = PlayedHole.create!(hole_id: timber_terrace_four.id, round_id: round.id, player_id: jeffery.id)
played_hole_five = PlayedHole.create!(hole_id: timber_terrace_five.id, round_id: round.id, player_id: jeffery.id)
played_hole_six = PlayedHole.create!(hole_id: timber_terrace_six.id, round_id: round.id, player_id: jeffery.id)
played_hole_seven = PlayedHole.create!(hole_id: timber_terrace_seven.id, round_id: round.id, player_id: jeffery.id)
played_hole_eight = PlayedHole.create!(hole_id: timber_terrace_eight.id, round_id: round.id, player_id: jeffery.id)
played_hole_nine = PlayedHole.create!(hole_id: timber_terrace_nine.id, round_id: round.id, player_id: jeffery.id)

Shot.create!(number: 1, played_hole: played_hole_one, round_id: round.id, club: one_wood, chunk: true)
Shot.create!(number: 2, played_hole: played_hole_one, round_id: round.id, club: three_iron, chunk: true)
Shot.create!(number: 3, played_hole: played_hole_one, round_id: round.id, club: three_iron, pure: true)
Shot.create!(number: 4, played_hole: played_hole_one, round_id: round.id, club: seven_iron, chunk: true)
Shot.create!(number: 5, played_hole: played_hole_one, round_id: round.id, club: sand_wedge, skull: true)
Shot.create!(number: 6, played_hole: played_hole_one, round_id: round.id, club: putter)
Shot.create!(number: 7, played_hole: played_hole_one, round_id: round.id, club: putter, cup: true)

Shot.create!(number: 1, played_hole: played_hole_two, round_id: round.id, club: one_wood, top: true)
Shot.create!(number: 2, played_hole: played_hole_two, round_id: round.id, club: three_iron, chunk: true, mulligan: true)
Shot.create!(number: 3, played_hole: played_hole_two, round_id: round.id, club: three_iron, pure: true)
Shot.create!(number: 4, played_hole: played_hole_two, round_id: round.id, club: five_iron, chunk: true)
Shot.create!(number: 5, played_hole: played_hole_two, round_id: round.id, club: five_iron, soft: true)
Shot.create!(number: 6, played_hole: played_hole_two, round_id: round.id, club: eight_iron, trick: true, hard: true)
Shot.create!(number: 7, played_hole: played_hole_two, round_id: round.id, club: putter)
Shot.create!(number: 8, played_hole: played_hole_two, round_id: round.id, club: putter)
Shot.create!(number: 9, played_hole: played_hole_two, round_id: round.id, club: putter, cup: true)

Shot.create!(number: 1, played_hole: played_hole_three, round_id: round.id, club: three_wood, pop_up: true)
Shot.create!(number: 2, played_hole: played_hole_three, round_id: round.id, club: five_iron, punch: true)
Shot.create!(number: 3, played_hole: played_hole_three, round_id: round.id, club: trouble_wedge, pure: true)
Shot.create!(number: 4, played_hole: played_hole_three, round_id: round.id, club: putter)
Shot.create!(number: 5, played_hole: played_hole_three, round_id: round.id, club: putter)
Shot.create!(number: 6, played_hole: played_hole_three, round_id: round.id, club: putter)

Shot.create!(number: 1, played_hole: played_hole_four, round_id: round.id, club: five_wood, top: true)
Shot.create!(number: 2, played_hole: played_hole_four, round_id: round.id, club: five_iron, top: true)
Shot.create!(number: 3, played_hole: played_hole_four, round_id: round.id, club: pitching_wedge, skull: true)
Shot.create!(number: 4, played_hole: played_hole_four, round_id: round.id, club: putter)
Shot.create!(number: 5, played_hole: played_hole_four, round_id: round.id, club: putter)
Shot.create!(number: 6, played_hole: played_hole_four, round_id: round.id, club: putter, cup: true)

Shot.create!(number: 1, played_hole: played_hole_five, round_id: round.id, club: one_wood, shank: true)
Shot.create!(number: 2, played_hole: played_hole_five, round_id: round.id, club: three_iron, pure: true)
Shot.create!(number: 3, played_hole: played_hole_five, round_id: round.id, club: three_iron, soft: true)
Shot.create!(number: 4, played_hole: played_hole_five, round_id: round.id, club: nine_iron, left: true)
Shot.create!(number: 5, played_hole: played_hole_five, round_id: round.id, club: sand_wedge, soft: true)
Shot.create!(number: 6, played_hole: played_hole_five, round_id: round.id, club: eight_iron, trick: true)
Shot.create!(number: 7, played_hole: played_hole_five, round_id: round.id, club: putter)
Shot.create!(number: 8, played_hole: played_hole_five, round_id: round.id, club: putter)
Shot.create!(number: 9, played_hole: played_hole_five, round_id: round.id, club: putter, cup: true)

Shot.create!(number: 1, played_hole: played_hole_six, round_id: round.id, club: three_iron, shank: true)
Shot.create!(number: 2, played_hole: played_hole_six, round_id: round.id, club: pitching_wedge, shank: true)
Shot.create!(number: 3, played_hole: played_hole_six, round_id: round.id, club: trouble_wedge, pull: true)
Shot.create!(number: 4, played_hole: played_hole_six, round_id: round.id, club: putter)
Shot.create!(number: 5, played_hole: played_hole_six, round_id: round.id, club: putter)
Shot.create!(number: 6, played_hole: played_hole_six, round_id: round.id, club: putter, cup: true)

Shot.create!(number: 1, played_hole: played_hole_seven, round_id: round.id, club: three_wood, top: true)
Shot.create!(number: 2, played_hole: played_hole_seven, round_id: round.id, club: three_iron, pure: true)
Shot.create!(number: 3, played_hole: played_hole_seven, round_id: round.id, club: three_wood, top: true)
Shot.create!(number: 4, played_hole: played_hole_seven, round_id: round.id, club: three_iron, left: true)
Shot.create!(number: 5, played_hole: played_hole_seven, round_id: round.id, club: sand_wedge, pure: true)
Shot.create!(number: 6, played_hole: played_hole_seven, round_id: round.id, club: putter)
Shot.create!(number: 7, played_hole: played_hole_seven, round_id: round.id, club: putter)
Shot.create!(number: 8, played_hole: played_hole_seven, round_id: round.id, club: putter, cup: true)

Shot.create!(number: 1, played_hole: played_hole_eight, round_id: round.id, club: three_iron, skull: true)
Shot.create!(number: 2, played_hole: played_hole_eight, round_id: round.id, club: eight_iron, trick: true)
Shot.create!(number: 3, played_hole: played_hole_eight, round_id: round.id, club: putter)
Shot.create!(number: 4, played_hole: played_hole_eight, round_id: round.id, club: putter, cup: true)

Shot.create!(number: 1, played_hole: played_hole_nine, round_id: round.id, club: three_wood, shank: true, mulligan: true)
Shot.create!(number: 2, played_hole: played_hole_nine, round_id: round.id, club: three_wood, top: true)
Shot.create!(number: 3, played_hole: played_hole_nine, round_id: round.id, club: three_wood, pull: true)
Shot.create!(number: 4, played_hole: played_hole_nine, round_id: round.id, club: one_wood, low: true)
Shot.create!(number: 5, played_hole: played_hole_nine, round_id: round.id, club: three_iron, shank: true)
Shot.create!(number: 6, played_hole: played_hole_nine, round_id: round.id, club: pitching_wedge, skull: true)
Shot.create!(number: 7, played_hole: played_hole_nine, round_id: round.id, club: eight_iron, trick: true)
Shot.create!(number: 8, played_hole: played_hole_nine, round_id: round.id, club: putter)
Shot.create!(number: 9, played_hole: played_hole_nine, round_id: round.id, club: putter)
Shot.create!(number: 10, played_hole: played_hole_nine, round_id: round.id, club: putter, cup: true)
